reconfigured tests

diff --git a/test/Makefile.in b/test/Makefile.in
--- a/test/Makefile.in
+++ b/test/Makefile.in
@@ -87,15 +87,18 @@ PACKAGE = @PACKAGE@
 RANLIB = @RANLIB@
 VERSION = @VERSION@
 
-check_PROGRAMS =  connect1 connect2 insert1 insert2 direct_exec1 read1 read2 malloctest insert3 direct_exec2 read3 rollback1 commit1
+check_PROGRAMS =  connect1 connect2 direct_exec1 direct_exec2 insert1 insert3 read1 read2 read3 malloctest rollback1 commit1 insert2 
 
 
 INCLUDES = -I${ODBCIDIR} -I../src
 
-EXTRA_DIST = 
+TESTS = $(check_PROGRAMS)
+EXTRA_DIST = runtests
 
 LDFLAGS =  	-L${ODBCLDIR} -lodbc ../src/mem_functions.o
 
+
+CLEANFILES = *.*~
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
 CONFIG_HEADER = ../config.h
 CONFIG_CLEAN_FILES = 
@@ -113,21 +116,26 @@ connect2_OBJECTS =  connect2.o
 connect2_LDADD = $(LDADD)
 connect2_DEPENDENCIES = 
 connect2_LDFLAGS = 
-insert1_SOURCES = insert1.c
-insert1_OBJECTS =  insert1.o
-insert1_LDADD = $(LDADD)
-insert1_DEPENDENCIES = 
-insert1_LDFLAGS = 
-insert2_SOURCES = insert2.c
-insert2_OBJECTS =  insert2.o
-insert2_LDADD = $(LDADD)
-insert2_DEPENDENCIES = 
-insert2_LDFLAGS = 
 direct_exec1_SOURCES = direct_exec1.c
 direct_exec1_OBJECTS =  direct_exec1.o
 direct_exec1_LDADD = $(LDADD)
 direct_exec1_DEPENDENCIES = 
 direct_exec1_LDFLAGS = 
+direct_exec2_SOURCES = direct_exec2.c
+direct_exec2_OBJECTS =  direct_exec2.o
+direct_exec2_LDADD = $(LDADD)
+direct_exec2_DEPENDENCIES = 
+direct_exec2_LDFLAGS = 
+insert1_SOURCES = insert1.c
+insert1_OBJECTS =  insert1.o
+insert1_LDADD = $(LDADD)
+insert1_DEPENDENCIES = 
+insert1_LDFLAGS = 
+insert3_SOURCES = insert3.c
+insert3_OBJECTS =  insert3.o
+insert3_LDADD = $(LDADD)
+insert3_DEPENDENCIES = 
+insert3_LDFLAGS = 
 read1_SOURCES = read1.c
 read1_OBJECTS =  read1.o
 read1_LDADD = $(LDADD)
@@ -138,26 +146,16 @@ read2_OBJECTS =  read2.o
 read2_LDADD = $(LDADD)
 read2_DEPENDENCIES = 
 read2_LDFLAGS = 
-malloctest_SOURCES = malloctest.c
-malloctest_OBJECTS =  malloctest.o
-malloctest_LDADD = $(LDADD)
-malloctest_DEPENDENCIES = 
-malloctest_LDFLAGS = 
-insert3_SOURCES = insert3.c
-insert3_OBJECTS =  insert3.o
-insert3_LDADD = $(LDADD)
-insert3_DEPENDENCIES = 
-insert3_LDFLAGS = 
-direct_exec2_SOURCES = direct_exec2.c
-direct_exec2_OBJECTS =  direct_exec2.o
-direct_exec2_LDADD = $(LDADD)
-direct_exec2_DEPENDENCIES = 
-direct_exec2_LDFLAGS = 
 read3_SOURCES = read3.c
 read3_OBJECTS =  read3.o
 read3_LDADD = $(LDADD)
 read3_DEPENDENCIES = 
 read3_LDFLAGS = 
+malloctest_SOURCES = malloctest.c
+malloctest_OBJECTS =  malloctest.o
+malloctest_LDADD = $(LDADD)
+malloctest_DEPENDENCIES = 
+malloctest_LDFLAGS = 
 rollback1_SOURCES = rollback1.c
 rollback1_OBJECTS =  rollback1.o
 rollback1_LDADD = $(LDADD)
@@ -168,6 +166,11 @@ commit1_OBJECTS =  commit1.o
 commit1_LDADD = $(LDADD)
 commit1_DEPENDENCIES = 
 commit1_LDFLAGS = 
+insert2_SOURCES = insert2.c
+insert2_OBJECTS =  insert2.o
+insert2_LDADD = $(LDADD)
+insert2_DEPENDENCIES = 
+insert2_LDFLAGS = 
 CFLAGS = @CFLAGS@
 COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
 LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
@@ -184,8 +187,8 @@ DEP_FILES =  .deps/commit1.P .deps/connect1.P .deps/connect2.P \
 .deps/direct_exec1.P .deps/direct_exec2.P .deps/insert1.P \
 .deps/insert2.P .deps/insert3.P .deps/malloctest.P .deps/read1.P \
 .deps/read2.P .deps/read3.P .deps/rollback1.P
-SOURCES = connect1.c connect2.c insert1.c insert2.c direct_exec1.c read1.c read2.c malloctest.c insert3.c direct_exec2.c read3.c rollback1.c commit1.c
-OBJECTS = connect1.o connect2.o insert1.o insert2.o direct_exec1.o read1.o read2.o malloctest.o insert3.o direct_exec2.o read3.o rollback1.o commit1.o
+SOURCES = connect1.c connect2.c direct_exec1.c direct_exec2.c insert1.c insert3.c read1.c read2.c read3.c malloctest.c rollback1.c commit1.c insert2.c
+OBJECTS = connect1.o connect2.o direct_exec1.o direct_exec2.o insert1.o insert3.o read1.o read2.o read3.o malloctest.o rollback1.o commit1.o insert2.o
 
 all: all-redirect
 .SUFFIXES:
@@ -247,17 +250,21 @@ connect2: $(connect2_OBJECTS) $(connect2_DEPENDENCIES)
 	@rm -f connect2
 	$(LINK) $(connect2_LDFLAGS) $(connect2_OBJECTS) $(connect2_LDADD) $(LIBS)
 
+direct_exec1: $(direct_exec1_OBJECTS) $(direct_exec1_DEPENDENCIES)
+	@rm -f direct_exec1
+	$(LINK) $(direct_exec1_LDFLAGS) $(direct_exec1_OBJECTS) $(direct_exec1_LDADD) $(LIBS)
+
+direct_exec2: $(direct_exec2_OBJECTS) $(direct_exec2_DEPENDENCIES)
+	@rm -f direct_exec2
+	$(LINK) $(direct_exec2_LDFLAGS) $(direct_exec2_OBJECTS) $(direct_exec2_LDADD) $(LIBS)
+
 insert1: $(insert1_OBJECTS) $(insert1_DEPENDENCIES)
 	@rm -f insert1
 	$(LINK) $(insert1_LDFLAGS) $(insert1_OBJECTS) $(insert1_LDADD) $(LIBS)
 
-insert2: $(insert2_OBJECTS) $(insert2_DEPENDENCIES)
-	@rm -f insert2
-	$(LINK) $(insert2_LDFLAGS) $(insert2_OBJECTS) $(insert2_LDADD) $(LIBS)
-
-direct_exec1: $(direct_exec1_OBJECTS) $(direct_exec1_DEPENDENCIES)
-	@rm -f direct_exec1
-	$(LINK) $(direct_exec1_LDFLAGS) $(direct_exec1_OBJECTS) $(direct_exec1_LDADD) $(LIBS)
+insert3: $(insert3_OBJECTS) $(insert3_DEPENDENCIES)
+	@rm -f insert3
+	$(LINK) $(insert3_LDFLAGS) $(insert3_OBJECTS) $(insert3_LDADD) $(LIBS)
 
 read1: $(read1_OBJECTS) $(read1_DEPENDENCIES)
 	@rm -f read1
@@ -267,21 +274,13 @@ read2: $(read2_OBJECTS) $(read2_DEPENDENCIES)
 	@rm -f read2
 	$(LINK) $(read2_LDFLAGS) $(read2_OBJECTS) $(read2_LDADD) $(LIBS)
 
-malloctest: $(malloctest_OBJECTS) $(malloctest_DEPENDENCIES)
-	@rm -f malloctest
-	$(LINK) $(malloctest_LDFLAGS) $(malloctest_OBJECTS) $(malloctest_LDADD) $(LIBS)
-
-insert3: $(insert3_OBJECTS) $(insert3_DEPENDENCIES)
-	@rm -f insert3
-	$(LINK) $(insert3_LDFLAGS) $(insert3_OBJECTS) $(insert3_LDADD) $(LIBS)
-
-direct_exec2: $(direct_exec2_OBJECTS) $(direct_exec2_DEPENDENCIES)
-	@rm -f direct_exec2
-	$(LINK) $(direct_exec2_LDFLAGS) $(direct_exec2_OBJECTS) $(direct_exec2_LDADD) $(LIBS)
-
 read3: $(read3_OBJECTS) $(read3_DEPENDENCIES)
 	@rm -f read3
 	$(LINK) $(read3_LDFLAGS) $(read3_OBJECTS) $(read3_LDADD) $(LIBS)
+
+malloctest: $(malloctest_OBJECTS) $(malloctest_DEPENDENCIES)
+	@rm -f malloctest
+	$(LINK) $(malloctest_LDFLAGS) $(malloctest_OBJECTS) $(malloctest_LDADD) $(LIBS)
 
 rollback1: $(rollback1_OBJECTS) $(rollback1_DEPENDENCIES)
 	@rm -f rollback1
@@ -290,6 +289,10 @@ rollback1: $(rollback1_OBJECTS) $(rollback1_DEPENDENCIES)
 commit1: $(commit1_OBJECTS) $(commit1_DEPENDENCIES)
 	@rm -f commit1
 	$(LINK) $(commit1_LDFLAGS) $(commit1_OBJECTS) $(commit1_LDADD) $(LIBS)
+
+insert2: $(insert2_OBJECTS) $(insert2_DEPENDENCIES)
+	@rm -f insert2
+	$(LINK) $(insert2_LDFLAGS) $(insert2_OBJECTS) $(insert2_LDADD) $(LIBS)
 
 tags: TAGS
 
@@ -372,12 +375,38 @@ maintainer-clean-depend:
 	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
 	    >> .deps/$(*F).P; \
 	rm -f .deps/$(*F).pp
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
 	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
@@ -402,6 +431,7 @@ installdirs:
 mostlyclean-generic:
 
 clean-generic:
+	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)
 
 distclean-generic:
 	-rm -f Makefile $(CONFIG_CLEAN_FILES)
@@ -441,10 +471,10 @@ distclean-compile clean-compile maintainer-clean-compile \
 mostlyclean-libtool distclean-libtool clean-libtool \
 maintainer-clean-libtool tags mostlyclean-tags distclean-tags \
 clean-tags maintainer-clean-tags distdir mostlyclean-depend \
-distclean-depend clean-depend maintainer-clean-depend info-am info \
-dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
-install-exec install-data-am install-data install-am install \
-uninstall-am uninstall all-redirect all-am all installdirs \
+distclean-depend clean-depend maintainer-clean-depend check-TESTS \
+info-am info dvi-am dvi check check-am installcheck-am installcheck \
+install-exec-am install-exec install-data-am install-data install-am \
+install uninstall-am uninstall all-redirect all-am all installdirs \
 mostlyclean-generic distclean-generic clean-generic \
 maintainer-clean-generic clean mostlyclean distclean maintainer-clean
 
